#!/bin/bash

NVIM_FOLDER=~/.config/nvim
LAZY_FOLDER=~/.local/share/nvim/lazy

is_program_installed() {
  if command -v "$1" >/dev/null 2>&1; then
	  printf "y"
  else
	  printf "n"
  fi
}

was_found_cask() {
  if brew list --cask | grep -q "$1"; then
	  printf "y"
  else
	  printf "n"
  fi
}

folder_exists() {
  if [ -d "$1" ]; then
	  printf "y"
  else
	  printf "n"
  fi
}

file_exists() {
  if [ -f "$1" ]; then
    printf "y"
  else
    printf "n"
  fi
}

install_homebrew() {
  if [ "$(is_program_installed "brew")" = "y" ]; then
  	echo "Brew is installed"
  else
  	echo "Installing Brew"
	  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	  echo "Brew was installed"
  fi
}

install_brew_nerd_font() {
  if [ "$(was_found_cask "font-meslo-lg-nerd-font")" = "y" ]; then
	  echo "Font Meslo Lg Nerd Font is installed"
  else
	  brew install font-meslo-lg-nerd-font
	  echo "font-meslo-lg-nerd-font was installed"
  fi
}

install_brew_neovim() {
  if [ "$(is_program_installed "nvim")" = "y" ]; then
	  echo "Neovim is installed"
  else
	  brew install neovim
	  echo "Neovim was installed"
  fi
}

install_brew_ripgrep() {
  if [ "$(is_program_installed "rg")" = "y" ]; then
	  echo "Ripgrep is installed"
  else
	  brew install ripgrep
	  echo "Ripgrep was installed"
  fi
}

create_nvim_directory() {
  if [ "$(folder_exists "$NVIM_FOLDER")" = "y" ]; then
	  echo "nvim folder exists"
  else
    cp -a -p ./nvim $NVIM_FOLDER
	  echo "nvim folder was created"
  fi
}

create_lazy_nvim_folder() {
  res="$(folder_exists "$LAZY_FOLDER/lazy.nvim")"
  if [ "$res" = "y" ]; then
    echo "lazy.nvim folder exists"
  else
    mkdir -p "$LAZY_FOLDER"
    git clone https://github.com/folke/lazy.nvim.git ~/.local/share/nvim/lazy/lazy.nvim
    echo "lazy.nvim folder was created"
  fi
}

install_homebrew
install_brew_nerd_font
install_brew_neovim
install_brew_ripgrep
create_nvim_directory
create_lazy_nvim_folder
